service: serverless-workshop-exercise-3

provider:
    name: aws
    runtime: nodejs12.x

plugins:
    - serverless-dotenv-plugin

functions:
    hello:
        handler: dist/hello.handler
        events:
            - http:
                  path: hello
                  method: GET
                  cors: true

    # add a sendSMS function here
    # use POST
    sendSMS:
        handler: dist/send-sms.handler
        events:
            - http:
                  path: sendsms
                  method: POST
                  cors: true
