service: serverless-workshop-exercise-3

provider:
    name: aws
    runtime: nodejs12.x
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:${self:provider.region}:*"

plugins:
    - serverless-dotenv-plugin

functions:
    hello:
        handler: dist/hello.handler
        events:
            - http:
                  path: hello
                  method: GET
                  cors: true

    # add a sendSMS function here
    # use POST
    sendSMS:
        handler: dist/send-sms.handler
        events:
            - http:
                  path: sendsms
                  method: POST
                  cors: true

package:
    exclude:
        - node_modules/typescript/**
