service: serverless-workshop-exercise-6

provider:
    name: aws
    runtime: nodejs12.x
    # dynamodb permissions here

functions:
    # add updateItem function here
    # add getItem function here
# define dynamodb here

package:
    exclude:
        - node_modules/typescript/**
