service: serverless-workshop-exercise-6

provider:
    name: aws
    runtime: nodejs12.x
    # dynamodb permissions here
    environment:
        ITEMS_TABLE: ${self:service}-items-${self:provider.stage}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ITEMS_TABLE}"

functions:
    # add updateItem function here
    updateItem:
        handler: dist/updateItem.handler
        events:
            - http:
                  path: update/{itemId}
                  method: POST
                  cors: true
    # add getItem function here
    getItem:
        handler: dist/getItem.handler
        events:
            - http:
                  path: get/{itemId}
                  method: GET
                  cors: true
# define dynamodb here

resources:
    - ${file(dynamodb.yml)}

plugin:
    - serverless-resources-env
