service: serverless-workshop-exercise-1

provider:
    name: aws
    runtime: nodejs12.x

functions:
    hello:
        handler: dist/hello.handler
        events:
            - http:
                  path: hello
                  method: GET
                  cors: true

package:
    exclude:
        - node_modules/typescript/**
