service: serverless-workshop-exercise-4

provider:
    name: aws
    runtime: nodejs12.x

functions:
    hello:
        handler: dist/hello.handler
        events:
            - http:
                  path: hello
                  method: GET
                  cors: true

    # add your take-screenshot function here
# add your package config here
