Resources:
    UpvotesTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions:
                - AttributeName: itemId
                  AttributeType: S
                - AttributeName: voteId
                  AttributeType: S
            KeySchema:
                - AttributeName: itemId
                  KeyType: HASH
                - AttributeName: voteId
                  KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            TableName: ${self:provider.environment.UPVOTES_TABLE}
